name: Ordering CI

on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: 'Set image Version flag'
      run: echo "version=$(date +%s)"  >> $GITHUB_ENV
        
    - name: 'Print the image version'
      run: echo "${{ env.version }}"
