name: Payment CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: 'Set image Version flag'
      run: echo "version=$(date +%s)"  >> $GITHUB_ENV
        
    - name: 'Print the image version'
      run: echo "${{ env.version }}"
      
    - name: Build the Docker image
      run: docker build . --file SampleApp/Payment/Dockerfile --tag hasitha2kandy/sample-dotnet-app:payment-api-${{env.version}}

    - name: Tag the Latest image
      run: docker tag hasitha2kandy/sample-dotnet-app:payment-api-${{env.version}} hasitha2kandy/sample-dotnet-app:payment-api-latest
      
    - name: Push images to Docker Hub
      run: |
        docker push hasitha2kandy/sample-dotnet-app:payment-api-${{env.version}}
        docker push hasitha2kandy/sample-dotnet-app:payment-api-latest
